INSERT INTO states VALUES
  (1, 'ID', 'ACEH', '-', 'now()', 'now()'),
  ('6728', 'ID', 'SUMATERA UTARA', '-', 'now()', 'now()'),
  ('12920', 'ID', 'SUMATERA BARAT', '-', 'now()', 'now()'),
  ('14086', 'ID', 'RIAU', '-', 'now()', 'now()'),
  ('15885', 'ID', 'JAMBI', '-', 'now()', 'now()'),
  ('17404', 'ID', 'SUMATERA SELATAN', '-', 'now()', 'now()'),
  ('20802', 'ID', 'BENGKULU', '-', 'now()', 'now()'),
  ('22328', 'ID', 'LAMPUNG', '-', 'now()', 'now()'),
  ('24993', 'ID', 'KEPULAUAN BANGKA BELITUNG', '-', 'now()', 'now()'),
  ('25405', 'ID', 'KEPULAUAN RIAU', '-', 'now()', 'now()'),
  ('25823', 'ID', 'DKI JAKARTA', '-', 'now()', 'now()'),
  ('26141', 'ID', 'JAWA BARAT', '-', 'now()', 'now()'),
  ('32676', 'ID', 'JAWA TENGAH', '-', 'now()', 'now()'),
  ('41863', 'ID', 'DAERAH ISTIMEWA YOGYAKARTA', '-', 'now()', 'now()'),
  ('42385', 'ID', 'JAWA TIMUR', '-', 'now()', 'now()'),
  ('51578', 'ID', 'BANTEN', '-', 'now()', 'now()'),
  ('53241', 'ID', 'BALI', '-', 'now()', 'now()'),
  ('54020', 'ID', 'NUSA TENGGARA BARAT', '-', 'now()', 'now()'),
  ('55065', 'ID', 'NUSA TENGGARA TIMUR', '-', 'now()', 'now()'),
  ('58285', 'ID', 'KALIMANTAN BARAT', '-', 'now()', 'now()'),
  ('60371', 'ID', 'KALIMANTAN TENGAH', '-', 'now()', 'now()'),
  ('61965', 'ID', 'KALIMANTAN SELATAN', '-', 'now()', 'now()'),
  ('64111', 'ID', 'KALIMANTAN TIMUR', '-', 'now()', 'now()'),
  ('65702', 'ID', 'SULAWESI UTARA', '-', 'now()', 'now()'),
  ('67393', 'ID', 'SULAWESI TENGAH', '-', 'now()', 'now()'),
  ('69268', 'ID', 'SULAWESI SELATAN', '-', 'now()', 'now()'),
  ('72551', 'ID', 'SULAWESI TENGGARA', '-', 'now()', 'now()'),
  ('74716', 'ID', 'GORONTALO', '-', 'now()', 'now()'),
  ('75425', 'ID', 'SULAWESI BARAT', '-', 'now()', 'now()'),
  ('76096', 'ID', 'MALUKU', '-', 'now()', 'now()'),
  ('77085', 'ID', 'MALUKU UTARA', '-', 'now()', 'now()'),
  ('78203', 'ID', 'PAPUA', '-', 'now()', 'now()'),
  ('81877', 'ID', 'PAPUA BARAT', '-', 'now()', 'now()');
